[Service]
ExecStartPre=/usr/bin/ctr --namespace k8s.io images import --local --platform linux/arm64 --snapshotter native /etc/eks/pause.tar
ExecStartPre=/usr/bin/ctr --namespace k8s.io images tag --force docker.io/floci/eks-pause:3.10-arm64 localhost/kubernetes/pause:latest
