package io.github.hectorvent.floci.services.iam;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Which of IAM's own resources each IAM action is authorized against, read once from the vendored
 * {@code aws/iam-action-resources.json}.
 *
 * <p>The file is generated by {@code tools/aws/regen_iam_action_resources.py} from AWS's Service
 * Reference Information for IAM
 * (https://servicereference.us-east-1.amazonaws.com/v1/iam/iam.json). It is vendored rather than
 * derived because the resource an IAM action acts on is not in the request:
 * {@code AddUserToGroup} carries a {@code UserName} and a {@code GroupName} and is authorized
 * against the group, {@code AddRoleToInstanceProfile} carries a {@code RoleName} and is authorized
 * against the instance profile, and {@code EnableMFADevice} carries a {@code SerialNumber} and is
 * authorized against the user rather than the device. Reading the type off the parameters would
 * scope those to the wrong resource and let a deny on the right one pass.
 *
 * <p>{@code make iam-action-resources-check} gates its shape offline and
 * {@code make iam-action-resources-verify} checks every claim in it against AWS, so a type that
 * drifts from what AWS publishes fails in CI rather than quietly authorizing against the wrong
 * resource. {@link ResourceArnBuilder} is the only consumer.
 *
 * <p>An action absent from the file is one AWS does not publish, which is different from an action
 * published with no resource type: the first is a gap, the second is a wildcard on purpose. Both
 * read as {@link #typesOf} returning an empty list, and the caller treats both as {@code *}, but
 * the distinction is why resource-less actions are still listed with an empty list rather than
 * left out.
 *
 * <p>A missing or malformed resource is a build defect, not a runtime condition, so loading fails
 * with {@link IllegalStateException} rather than degrading to an empty map, which would silently
 * put every IAM action back on the wildcard.
 */
public final class IamActionResources {

    static final String RESOURCE_NAME = "aws/iam-action-resources.json";

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private static final class Holder {
        static final Catalog CATALOG = load();
    }

    /** The two halves of the vendored file: what each action names, and how each type is spelled. */
    record Catalog(Map<String, List<String>> actionResources,
                   Map<String, List<String>> resourceArnFormats) {
    }

    private IamActionResources() {
    }

    /**
     * The resource types AWS authorizes {@code action} against, or an empty list when it
     * authorizes against none and when the action is one AWS does not publish.
     */
    public static List<String> typesOf(String action) {
        if (action == null) {
            return List.of();
        }
        return Holder.CATALOG.actionResources().getOrDefault(action, List.of());
    }

    /** Every resource type AWS publishes an ARN format for, with those formats. */
    public static Map<String, List<String>> arnFormats() {
        return Holder.CATALOG.resourceArnFormats();
    }

    /** Every action the file carries, which is every action AWS publishes for IAM. */
    public static Map<String, List<String>> all() {
        return Holder.CATALOG.actionResources();
    }

    private static Catalog load() {
        try (InputStream in = Thread.currentThread().getContextClassLoader()
                .getResourceAsStream(RESOURCE_NAME)) {
            if (in == null) {
                throw new IllegalStateException("IAM action resource catalog resource not found: "
                        + RESOURCE_NAME);
            }
            return parse(in);
        } catch (IOException e) {
            throw new IllegalStateException("Failed to read the IAM action resource catalog "
                    + RESOURCE_NAME, e);
        }
    }

    static Catalog parse(InputStream in) throws IOException {
        JsonNode root = MAPPER.readTree(in);
        Map<String, List<String>> actions = readLists(root.path("actionResources"),
                "actionResources");
        Map<String, List<String>> formats = readLists(root.path("resourceArnFormats"),
                "resourceArnFormats");
        for (Map.Entry<String, List<String>> entry : actions.entrySet()) {
            for (String type : entry.getValue()) {
                if (!formats.containsKey(type)) {
                    throw new IllegalStateException(RESOURCE_NAME + " has " + entry.getKey()
                            + " naming the resource type " + type + ", which has no ARN format");
                }
            }
        }
        return new Catalog(actions, formats);
    }

    private static Map<String, List<String>> readLists(JsonNode node, String field) {
        if (!node.isObject() || node.isEmpty()) {
            throw new IllegalStateException(RESOURCE_NAME + " carries no " + field);
        }
        Map<String, List<String>> parsed = new LinkedHashMap<>();
        node.properties().forEach(entry -> {
            JsonNode values = entry.getValue();
            if (!values.isArray()) {
                throw new IllegalStateException(RESOURCE_NAME + " has " + field + "."
                        + entry.getKey() + " as something other than a list");
            }
            List<String> read = new ArrayList<>(values.size());
            for (JsonNode value : values) {
                String text = value.asText("");
                if (text.isBlank()) {
                    throw new IllegalStateException(RESOURCE_NAME + " has a blank entry under "
                            + field + "." + entry.getKey());
                }
                read.add(text);
            }
            parsed.put(entry.getKey(), List.copyOf(read));
        });
        return Map.copyOf(parsed);
    }
}
