package io.github.hectorvent.floci.services.iam;

import io.github.hectorvent.floci.core.common.ServicePrincipals;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;

/**
 * What AWS does with a service-linked role for a given service principal, from
 * {@code iam/service-linked-roles.tsv}.
 *
 * <p>Two things about a service-linked role cannot be worked out from the principal. The role name
 * is not a capitalisation of it: {@code acm.amazonaws.com} gives
 * {@code AWSServiceRoleForCertificateManager}, and deriving it is wrong for most of the services
 * the table covers. And whether the service takes a {@code CustomSuffix} varies, which the API
 * Reference says without saying which services those are.
 *
 * <p>The table is generated by {@code tools/slr/service_linked_roles.py} from AWS evidence, and
 * {@code make slr-check} gates it. Each row records the authority it rests on, so a name that
 * nothing can confirm is visible as such rather than looking like the rest.
 *
 * <p>A principal the table does not cover keeps the old derived name and keeps accepting a suffix.
 * Both are deliberate: inventing a refusal for a service no recording covers would be worse than
 * accepting one AWS might reject, and the derived name is at least what this emulator has always
 * returned.
 */
public final class ServiceLinkedRoles {

    /** Whether AWS accepts a {@code CustomSuffix} for a service, as far as anything records it. */
    public enum CustomSuffixSupport {
        /** A recorded create accepted a suffix. */
        ALLOWED,
        /** A recorded create answered {@code InvalidInput} for a suffix. */
        REFUSED,
        /** No recording covers it, so the suffix is accepted rather than refused on a guess. */
        UNKNOWN
    }

    /** One row: the principal, the role AWS mints, suffix support, and where that came from. */
    public record Entry(String principal, String roleName, CustomSuffixSupport customSuffix,
                        String source) {
    }

    static final String ROLE_NAME_PREFIX = "AWSServiceRoleFor";
    private static final String RESOURCE_NAME = "iam/service-linked-roles.tsv";
    private static final Map<String, Entry> BY_PRINCIPAL = load();

    private ServiceLinkedRoles() {
    }

    /** The row for a principal in any partition form, empty when the table does not cover it. */
    public static Optional<Entry> find(String awsServiceName) {
        if (awsServiceName == null) {
            return Optional.empty();
        }
        return Optional.ofNullable(BY_PRINCIPAL.get(ServicePrincipals.canonical(awsServiceName)));
    }

    /**
     * The role name AWS mints for a principal, falling back to the derived form.
     *
     * <p>Returns empty only when the principal carries nothing to derive a name from, which is a
     * {@code ValidationError} for the caller to raise rather than a name of {@code AWSServiceRoleFor}.
     */
    public static Optional<String> roleName(String awsServiceName) {
        Optional<Entry> entry = find(awsServiceName);
        if (entry.isPresent()) {
            return Optional.of(entry.get().roleName());
        }
        String derived = derivedRoleName(awsServiceName);
        return ROLE_NAME_PREFIX.equals(derived) ? Optional.empty() : Optional.of(derived);
    }

    /** Suffix support for a principal, {@code UNKNOWN} when nothing records it. */
    public static CustomSuffixSupport customSuffixSupport(String awsServiceName) {
        return find(awsServiceName).map(Entry::customSuffix).orElse(CustomSuffixSupport.UNKNOWN);
    }

    /**
     * The name this emulator derived before the table existed: the principal's service part with
     * each dot- or hyphen-delimited segment capitalised. Kept as the fallback, and kept here rather
     * than in the caller so the generator's own fallback has one counterpart to match.
     *
     * <p>Every label contributes, because the leading one alone is not unique:
     * {@code rds.amazonaws.com} and {@code rds.application-autoscaling.amazonaws.com} are separate
     * roles on AWS, and both must not collapse onto one name here.
     */
    static String derivedRoleName(String awsServiceName) {
        String core = awsServiceName == null ? "" : ServicePrincipals.serviceName(awsServiceName);
        StringBuilder derived = new StringBuilder(ROLE_NAME_PREFIX);
        for (String segment : core.split("[.\\-]")) {
            if (!segment.isEmpty()) {
                derived.append(Character.toUpperCase(segment.charAt(0))).append(segment.substring(1));
            }
        }
        return derived.toString();
    }

    /** Every row, in the table's order, for tests that hold the tree to it. */
    static Map<String, Entry> all() {
        return BY_PRINCIPAL;
    }

    private static Map<String, Entry> load() {
        try (InputStream in = Thread.currentThread().getContextClassLoader()
                .getResourceAsStream(RESOURCE_NAME)) {
            if (in == null) {
                throw new IllegalStateException(
                        "service-linked role table not found on the classpath: " + RESOURCE_NAME);
            }
            Map<String, Entry> rows = new LinkedHashMap<>();
            BufferedReader reader = new BufferedReader(
                    new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            while ((line = reader.readLine()) != null) {
                String trimmed = line.strip();
                if (trimmed.isEmpty() || trimmed.startsWith("#")) {
                    continue;
                }
                String[] columns = trimmed.split("\t");
                if (columns.length != 4) {
                    throw new IllegalStateException(
                            RESOURCE_NAME + " needs four tab-separated columns, got: " + trimmed);
                }
                Entry entry = new Entry(columns[0], columns[1],
                        CustomSuffixSupport.valueOf(columns[2].toUpperCase(Locale.ROOT)), columns[3]);
                rows.put(entry.principal(), entry);
            }
            // Not Map.copyOf: that does not keep insertion order, and the table is sorted
            // by principal, so iterating it in file order keeps a failure message readable.
            return Collections.unmodifiableMap(rows);
        } catch (IOException e) {
            throw new IllegalStateException("cannot read " + RESOURCE_NAME, e);
        }
    }
}
